name: Set up build environment and dependencies

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        # cache: gradle

    # cache any custom dependencies (e.g. processing-core.zip) in the library/
    # folder so that they don't have to be downloaded every time
    - uses: actions/cache@v3
      with:
        key: deps-1
        path: library/
