name: "Pull request > test and build library zip"

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up build environment and dependencies
        uses: ./.github/actions/setup
      - name: Compile
        run: ant compile
      - name: Run tests
        run: ant test
      - name: Build library zip
        run: ant dist
