name: "Commit > Build library jar, run tests and publish Javadoc"

on:
  push:
    branches: [ 'main' ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup.yml
      - name: Build library with Ant
        run: ant jar
      - name: Run tests
        run: ant test
      - uses: actions/upload-artifact@v3
        with:
          name: sound-jar-${{ github.sha }}
          path: library/sound.jar
      - name: Build Javadoc
        run: ant javadoc
      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/


  deploy-javadoc:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
