name: Create Github release

on:
  push:
    tags: [ '*' ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and package library with Ant
        run: ant dist

        # https://stackoverflow.com/questions/63745613/how-to-get-a-branch-name-on-github-action-when-push-on-a-tag
      - name: Get branch name
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          echo "BRANCH=$(echo ${raw##*/})" >> $GITHUB_ENV

      - name: Create test build release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          body: Test build of commit ${{ github.sha }} from the [${{ env.BRANCH }}](${{ github.repositoryUrl }}/tree/TODO) branch
          files: ../sound.zip

